<?php

namespace WCS\CoavBundle\Repository;

/**
 * ReviwRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviwRepository extends \Doctrine\ORM\EntityRepository
{
}
